"""Add HistoricalValue model

Revision ID: 085813102fba
Revises: b36fa7fdf585
Create Date: 2024-07-13 19:21:18.503172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085813102fba'
down_revision: Union[str, None] = 'b36fa7fdf585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_values_date'), 'historical_values', ['date'], unique=False)
    op.create_index(op.f('ix_historical_values_id'), 'historical_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_values_id'), table_name='historical_values')
    op.drop_index(op.f('ix_historical_values_date'), table_name='historical_values')
    op.drop_table('historical_values')
    # ### end Alembic commands ###
