"""New migration

Revision ID: 575de043450c
Revises: dfff29bb6f42
Create Date: 2024-07-13 19:08:30.563633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575de043450c'
down_revision: Union[str, None] = 'dfff29bb6f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_values_date', table_name='historical_values')
    op.drop_index('ix_historical_values_id', table_name='historical_values')
    op.drop_table('historical_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='historical_values_stock_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historical_values_pkey')
    )
    op.create_index('ix_historical_values_id', 'historical_values', ['id'], unique=False)
    op.create_index('ix_historical_values_date', 'historical_values', ['date'], unique=False)
    # ### end Alembic commands ###
