"""Add asset_type and make current_price nullable

Revision ID: 58f995579334
Revises: 76e3b1ceb360
Create Date: 2024-07-19 14:09:14.755478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f995579334'
down_revision: Union[str, None] = '76e3b1ceb360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_name', table_name='assets')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_table('assets')
    op.add_column('stocks', sa.Column('asset_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'asset_type')
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='assets_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey')
    )
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=True)
    op.create_index('ix_assets_name', 'assets', ['name'], unique=False)
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    # ### end Alembic commands ###
