"""Add description to portfolios table

Revision ID: 97ca8a262b0b
Revises: f76f434a8e5c
Create Date: 2024-06-30 21:16:18.679489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ca8a262b0b'
down_revision: Union[str, None] = 'f76f434a8e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'description')
    # ### end Alembic commands ###
