"""Remove total_value and asset_count from portfolios table

Revision ID: c302da12a124
Revises: 34071a6fcf14
Create Date: 2024-06-30 20:39:50.849025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c302da12a124'
down_revision: Union[str, None] = '34071a6fcf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
